export default {
  code: 0,
  result: [
    {
      "title": "我的国潮时尚风搭配❗️❗️❗️",
      "avatar": "/static/images/avator1.jpg",
      "username": "奶糖",
      "thumbnail": "/static/images/thumbnail1.jpeg",
      "detail": ".........",
      "likesnum": 198,
      "liked": false,
    },
    {
      "title": "补一下最近的辅食～",
      "avatar": "/static/images/avator4.jpg",
      "username": "甜瓜🍈",
      "thumbnail": "/static/images/thumbnail4.jpeg",
      "detail": ".........",
      "likesnum": 203,
      "liked": false,
    },
    {
      "title": "6款最好吃的小零食，补钙养胃宝宝最爱❗️",
      "avatar": "/static/images/avator2.jpg",
      "username": "凡妈小厨房",
      "thumbnail": "/static/images/thumbnail2.jpeg",
      "detail": ".........",
      "likesnum": 34,
      "liked": true,
    },
    {
      "title": "我还是更喜欢我们老王家的😂",
      "avatar": "/static/images/avator3.jpg",
      "username": "🌻JC.Continue🍀",
      "thumbnail": "/static/images/thumbnail3.jpeg",
      "detail": ".........",
      "likesnum": 129,
      "liked": false,
    },
    {
      "title": "考研苦命党｜惊喜感满满的小众爱用品分享",
      "avatar": "/static/images/avator5.jpg",
      "username": "超级番茄",
      "thumbnail": "/static/images/thumbnail5.jpeg",
      "detail": ".........",
      "likesnum": 538,
      "liked": true,
    },
    {
      "title": "30岁的生日礼物🎁|生活旅行必备车🚙奥迪Q3而我访问无非为访问违法桑多瓦尔二分",
      "avatar": "/static/images/avator6.jpg",
      "username": "团子E菲🍡",
      "thumbnail": "/static/images/thumbnail6.jpeg",
      "detail": ".........",
      "likesnum": 208,
      "liked": false,
    },
    {
      "title": "老司机EDC大赏 | 这些都是直男的礼物🎁",
      "avatar": "/static/images/avator7.jpg",
      "username": "田大大官人",
      "thumbnail": "/static/images/thumbnail7.jpeg",
      "detail": ".........",
      "likesnum": 98,
      "liked": false,
    },
    {
      "title": "原来是它让Eva 秋天里亮丽冬天里温暖！",
      "avatar": "/static/images/avator8.jpg",
      "username": "混血宝贝Eva",
      "thumbnail": "/static/images/thumbnail8.jpeg",
      "detail": ".........",
      "likesnum": 56,
      "liked": true,
    },
    {
      "title": "漳州火山岛🎏国庆假期",
      "avatar": "/static/images/avator9.jpg",
      "username": "猫有鱼",
      "thumbnail": "/static/images/thumbnail9.jpeg",
      "detail": ".........",
      "likesnum": 88,
      "liked": true,
    },
    {
      "title": "懒人塑形💪🏻不去健身房也可以练出腹肌",
      "avatar": "/static/images/avator10.jpg",
      "username": "Bking👑饱饱",
      "thumbnail": "/static/images/thumbnail10.jpeg",
      "detail": ".........",
      "likesnum": 245,
      "liked": false,
    },
  ]
}
